### ISSUE TITLE
Cannot specify schema

### ISSUE THREAD

**Issue by jirokun** [maeharin/factlin#4]
使おうとトライしているのですが、複数スキーマで同名のテーブルがある場合、どちらも重複して一つのクラスが出来上がってしまいます。

スキーマを指定できるように機能拡張してもらえないでしょうか。

**Comment by maeharin** [comment]
@jirokun thank you for reporting issue. I will add that feature.

**Comment by maeharin** [comment]
@jirokun resolved #5, released v0.2.0
now you can specify schema(see: README)

ex:

```
// build.gradle
factlin {
    ....
    schema = "public"
}
```
